embed_assets: off

javascripts:
  light:
    - public/javascripts/lib/jquery.min.js
    - public/javascripts/lib/jquery_ujs.js

  heavy:
    - public/javascripts/lib/jquery.min.js
    - public/javascripts/lib/jquery_ujs.js
    - public/javascripts/lib/jquery.colorbox.js

  index:
    - public/javascripts/story-index.js

  edit:
    - public/javascripts/story-edit.js

  graphs:
    - public/javascripts/lib/raphael.js
    - public/javascripts/lib/g.raphael.js
    - public/javascripts/lib/g.pie.js
    - public/javascripts/story-reports.js

stylesheets:
  light:
    - public/stylesheets/style.css

  heavy:
    - public/stylesheets/style.css
    - public/stylesheets/colorbox.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
