embed_assets: off

javascripts:
  common:
    - public/javascripts/lib/jquery.min.js
    - public/javascripts/lib/jquery_ujs.js
    - public/javascripts/lib/jquery.twoup.js

  application:
    - public/javascripts/application.js

  index:
    - public/javascripts/story-index.js

  manipulate:
    - public/javascripts/story-edit.js

  graphs:
    - public/javascripts/lib/raphael.js
    - public/javascripts/lib/g.raphael.js
    - public/javascripts/lib/g.pie.js
    - public/javascripts/story-reports.js

stylesheets:
  common:
    - public/stylesheets/style.css

  heavy:
    - public/stylesheets/style.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
